name: Code Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.8", "3.12"]
      fail-fast: false
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4

    - name: Setup Micromamba env
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-name: TEST
        create-args: >-
          python=${{ matrix.python-version }}
          --file requirements.txt
          --file requirements-dev.txt

    - name: Install folium from source
      run: python -m pip install -e . --no-deps --force-reinstall

    - name: Code tests
      run: python -m pytest -vv --ignore=tests/selenium

    - name: Install nightly versions of dependencies
      run: python -m pip install --pre --index-url https://pypi.anaconda.org/scientific-python-nightly-wheels/simple --extra-index-url https://pypi.org/simple numpy pandas -U
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'

    - name: Code tests with nightly dependencies
      run: python -m pytest -vv --ignore=tests/selenium
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.12'
